### PR TITLE
Drop groovy, hirsute, and kinetic bundles

### PR DESCRIPTION
**Pull request by coreycb**
These are all EOL ubuntu releases that no longer require testing.

### CODE REVIEW

**Comment by freyes** [comment]
```
+ juju deploy --dry-run ./tests/octavia-upgrade/tests/bundles/octavia-focal-wallaby-ha-stable.yaml
...
ERROR cannot deploy bundle: cannot resolve charm or bundle "mysql-innodb-cluster": not found
```

```
  mysql-innodb-cluster:
    constraints: mem=3072M
    charm: cs:~openstack-charmers/mysql-innodb-cluster
    num_units: 3
```
https://github.com/openstack-charmers/charmed-openstack-tester/blob/master/tests/octavia-upgrade/tests/bundles/octavia-focal-wallaby-ha-stable.yaml#L36C1-L39C17

we still have bundles referencing `cs:`, are they used/needed?

**Comment by coreycb** [comment]
> ```
> + juju deploy --dry-run ./tests/octavia-upgrade/tests/bundles/octavia-focal-wallaby-ha-stable.yaml
> ...
> ERROR cannot deploy bundle: cannot resolve charm or bundle "mysql-innodb-cluster": not found
> ```
> 
> ```
>   mysql-innodb-cluster:
>     constraints: mem=3072M
>     charm: cs:~openstack-charmers/mysql-innodb-cluster
>     num_units: 3
> ```
> 
> https://github.com/openstack-charmers/charmed-openstack-tester/blob/master/tests/octavia-upgrade/tests/bundles/octavia-focal-wallaby-ha-stable.yaml#L36C1-L39C17
> 
> we still have bundles referencing `cs:`, are they used/needed?

There are a lot that use `cs:`. I'm not sure if they are still used or not. I think they were all used for release testing in the past?

**Comment by freyes** [comment]
https://github.com/openstack-charmers/charmed-openstack-tester/commit/63b97422ef751c0404bca9955f31d4b6026498aa

Alex may have some memories on this.

**Review by freyes — APPROVED** [review]
LGTM. This is the consequence of a discussion where there was agreement to deprecate the bundles != distro-regression

**Pull request merged**
