### PR TITLE
Switch distro yoga bundles to yoga/stable

### PR DESCRIPTION
**Pull request by coreycb**
The yoga/edge channel no longer exists so switch to yoga/stable.

### CODE REVIEW

**Review by ajkavanagh — CHANGES_REQUESTED** [review]
This is probably (almost certainly) not what you want.  If the yoga/stable track/risk doesn't exist then juju will fall back to the next 'more stable' risk for that track, all the way to "stable".  Thus if the bundle refers to 'edge' then it will get 'stable' if it doesn't exist.  If we have a candidate release (for example) of a charm, then that would be included in this bundle when testing against the 'stable' charms.  Unless this batch is *only* ever for stable and mustn't be used for candidate, beta, or edge charms in the process of being released, then I would leave this as yoga/edge.

**Comment by coreycb** [comment]
Thanks for the review. I'll have to try a deploy again (I'd had this change locally for a while) but I think at the time it was failing because yoga/edge didn't exist.

**Comment by coreycb** [comment]
I think all the yoga/edge channels disappeared from charmhub when yoga/stable was released.

**Comment by ajkavanagh** [comment]
> I think all the yoga/edge channels disappeared from charmhub when yoga/stable was released.

Yes, they did; we moved yoga/edge to yoga/candidate during release testing, and then to yoga/stable when it was released.  However, you can `juju deploy nova-compute --channel yoga/edge` and you will get the `yoga/stable` charm, as there is no `yoga/edge`; i.e. it falls back to the `yoga/stable` charm.  However, if we release a new `yoga/edge` release, then any bundles referring to `yoga/edge` will get that *in preference* to `yoga/stable`, which is what you want for testing, but not production.  As these are test bundles, that's what we want, isn't it?

**Comment by coreycb** [comment]
Confirmed that this is working as expected (as you've described Alex). It must not have been working at one point but regardless it is now, so that's good. I'm going to abandon this change.

**Pull request closed without merging**
